apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: traefik
spec:
  acme:
    email: gustavo@gbsoft.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
