apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.29.0
      helm:
        values: |
          loki:
            schemaConfig:
              configs:
                - from: 2024-04-01
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
            ingester:
              chunk_encoding: snappy
            tracing:
              enabled: false
            querier:
              max_concurrent: 4
            pattern_ingester:
              enabled: true
            limits_config:
              allow_structured_metadata: true
              volume_enabled: true
              retention_period: 72h
            auth_enabled: false
            storage:
              type: s3
              bucketNames:
                chunks: "loki"
                ruler: "loki"
                admin: "loki"
              s3:
                endpoint: "https://minio.minio-operator.svc.cluster.local"
                accessKeyId: "minio"
                secretAccessKey: "minio123"
                s3ForcePathStyle: true
                http_config:
                  insecure_skip_verify: true
          deploymentMode: SimpleScalable
          backend:
            replicas: 2
          read:
            replicas: 2
          write:
            replicas: 2
          minio:
            enabled: false
          chunksCache:
            enabled: false
          lokiCanary:
            enabled: false
          test:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
