apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.12.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            backupTarget: s3://gbsoft-homelab-longhorn-backup@us-east-2/
            backupTargetCredentialSecret: longhorn-backup-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
