apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  sources:
    - chart: tenant
      repoURL: https://operator.min.io
      targetRevision: 7.1.1
      helm:
        values: |
          tenant:
            pools:
              - servers: 2
                name: pool-0
                volumesPerServer: 2
                size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
