apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: operator
      repoURL: https://operator.min.io
      targetRevision: 7.1.1
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
