apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postiz
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/gitroomhq/postiz-helmchart/charts
      chart: postiz-app
      targetRevision: 1.0.5
    - repoURL: https://github.com/gmtborges/homelab.git
      path: argocd/manifests/postiz
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
