apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo-distributed
      targetRevision: 1.39.4
      helm:
        values: |
          storage:
            trace:
              backend: s3
              s3:
                access_key: "minio"
                secret_key: "minio123"
                bucket: "tempo"
                endpoint: "minio.minio-operator.svc.cluster.local"
                insecure: false
                tls_insecure_skip_verify: true

          minio:
            enabled: false

          traces:
            otlp:
              grpc:
                enabled: true
              http:
                enabled: true
            zipkin:
              enabled: false
            jaeger:
              thriftHttp:
                enabled: false
            opencensus:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
