apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://traefik.github.io/charts"
      targetRevision: 35.2.0
      chart: traefik
      helm:
        values: |
          providers:
            kubernetesGateway:
              enabled: true
          ingressRoute:
            dashboard:
              enabled: true
          gateway:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            listeners:
              websecure:
                port: 8443
                hostname: "*.gbsoft.net"
                protocol: HTTPS
                namespacePolicy: All
                certificateRefs:
                  - name: gbsoft-net-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
