# vim:ft=yaml.ansible
---
- name: Configure static IP using Netplan
  hosts: all
  become: true
  tasks:
    - name: Set the new hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
      notify: Update /etc/hosts with new hostname

    - name: Create a Netplan configuration for static IP
      ansible.builtin.copy:
        dest: /etc/netplan/99-custom.yaml
        content: |
          network:
            version: 2
            ethernets:
              ens18:
                dhcp4: false
                addresses:
                  - {{ ipv4_address }}/24
                nameservers:
                  addresses: {{ dns }}
                gateway4: {{ gateway4 }}
        mode: "644"
      register: netplan_config
      notify: Apply netplan config

    - name: Configure passwordless sudo for user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/nopasswd
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        mode: "0440"
        create: true
        validate: "/usr/sbin/visudo -cf %s"

  handlers:
    - name: Apply netplan config
      ansible.builtin.command: netplan apply
      async: 60
      poll: 0
      changed_when: netplan_config.changed

    - name: Update /etc/hosts with new hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1\\s+.*$"
        line: "127.0.1.1 {{ hostname }}"
